### ISSUE TITLE
there is a strange question that i only can use browser visit the first server. But i can use procedure to send a request to all servers.Why is that?

### ISSUE THREAD

**Issue by lhz-1236** [jimni/http-comparator#1]

**Comment by jimni** [comment]
Your browser might be incompatible with quic. Which server works for you?

Also, would be great to see the procedure you are using and some logs

**Comment by lhz-1236** [comment]
My browser is Chrome. i only made a small change to the code.
I  change 'h2quic.ListenAndServe(":8083", sslCert, sslKey, nil)' to 'h2quic.ListenAndServeQUIC(":8083", sslCert, sslKey, nil)'
and then i use Chrome to visit to 'https://localhost:8083'.However, the brower tell me "127.0.0.1:8083 rejected our connection request". And ,i am sure that i turned on quic.

**Comment by lhz-1236** [comment]
> Your browser might be incompatible with quic. Which server works for you?
> 
> Also, would be great to see the procedure you are using and some logs

**Comment by jimni** [comment]
Sorry dude, but there is no such line in my project (h2quic.ListenAndServe(":8083", sslCert, sslKey, nil))
So I don't think I could help much.

My only idea is that you're not using a valid certificate on your localhost (it's actually not that easy to make a valid localhost cert)
